### ISSUE TITLE
Fresh checkout cannot resolve GameObj

### ISSUE THREAD

**Issue by jasedit** [ondreian/norn.rb#1] opened 2017-08-26 14:29 UTC
I just made a fresh checkout, then ran:
1. `bin/setup`
2. `rake spec`

and receive a bunch of errors in the following fashion:
```
An error occurred while loading ./spec/game/game_spec.rb.
Failure/Error:
  class Hand < GameObj
    Empty   = Hand.new(:empty, :empty, :empty)
    @@store = MemoryStore.new
  
    def self.fetch(*args)
      @@store.fetch *args
    end
  
    def self.put(*args)
      @@store.put *args

NameError:
  uninitialized constant GameObj
# ./lib/norn/world/hand.rb:4:in `<top (required)>'
# ./lib/norn/parser/parser.rb:4:in `require'
# ./lib/norn/parser/parser.rb:4:in `block in <top (required)>'
# ./lib/norn/parser/parser.rb:4:in `each'
# ./lib/norn/parser/parser.rb:4:in `<top (required)>'
# ./lib/norn/world/gameobj.rb:1:in `require'
# ./lib/norn/world/gameobj.rb:1:in `<top (required)>'
# ./lib/norn/script/script.rb:3:in `require'
# ./lib/norn/script/script.rb:3:in `block in <top (required)>'
# ./lib/norn/script/script.rb:3:in `each'
# ./lib/norn/script/script.rb:3:in `<top (required)>'
# ./lib/norn/script/exec.rb:2:in `require'
# ./lib/norn/script/exec.rb:2:in `<top (required)>'
# ./lib/norn/game/game.rb:4:in `require'
# ./lib/norn/game/game.rb:4:in `<top (required)>'
# ./lib/norn.rb:5:in `require'
# ./lib/norn.rb:5:in `block in <top (required)>'
# ./lib/norn.rb:5:in `each'
# ./lib/norn.rb:5:in `<top (required)>'
# ./spec/spec_helper.rb:4:in `require'
# ./spec/spec_helper.rb:4:in `<top (required)>'
# ./spec/game/game_spec.rb:3:in `<top (required)>'
```

from what I can tell, it looks like there's a circular sequence of dependencies, in that `GameObj` requires the parser, and the parser requires `GameObj`, but I'm not 100% certain that's the actual issue. I can report that nothing can be loaded safely - even attempting to execute `require "norn/world/gameobj" produces errors about `GameObj` being uninitialized.

**Comment by ondreian** [comment] 2017-08-26 15:49
thanks.  this should be fixed now.  though there are likely still failing tests currently.  the Parser is still a bit of a WIP with all the edge cases.

**Comment by jasedit** [comment] 2017-08-26 15:53
I'm still getting this error with the latest version, even after re-running `bin/setup` - is there something else I need to do to resolve this? I've also tried running `bin/console` to test things working without the tests

**Comment by ondreian** [comment] 2017-08-26 16:04
hmm, travis & appveyor still seem to have issues with it.  Cannot reproduce locally however.

**Comment by jasedit** [comment] 2017-08-26 17:12
Could there be some earlier version tucked away elsewhere providing these classes? Or some alteration to the ruby path that needs to be done?

**Comment by ondreian** [comment] 2017-08-26 17:31
ok, try with the newest commit? seems to be fixed on CI.

**Comment by jasedit** [comment] 2017-08-26 17:42
Works for me now

**Closed** 2017-08-26 18:51 UTC
